/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface PredictionMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BONUS_AMOUNT"
      | "MAX_BET"
      | "MIN_BET"
      | "bonusPool"
      | "chainlinkOracleAddress"
      | "claimWinnings"
      | "emergencyWithdraw"
      | "fundBonusPool"
      | "getAIPrediction"
      | "getMatchStats"
      | "getPlatformStats"
      | "getPredictionDetails"
      | "getUserBet"
      | "getUserStats"
      | "hasBet"
      | "matchBets"
      | "matchPool"
      | "owner"
      | "placeBet"
      | "predictions"
      | "renounceOwnership"
      | "setChainlinkOracle"
      | "settleMatch"
      | "submitAIPrediction"
      | "totalBonusesPaid"
      | "totalMatchesCorrect"
      | "totalMatchesPredicted"
      | "totalVolumeTraded"
      | "transferOwnership"
      | "usdc"
      | "userBetIndex"
      | "userCorrectPredictions"
      | "userTotalBets"
      | "userTotalWinnings"
      | "winnersCount"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AIPredictionSubmitted"
      | "BetPlaced"
      | "BonusPoolFunded"
      | "MatchSettled"
      | "OracleAddressUpdated"
      | "OwnershipTransferred"
      | "WinningsClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BONUS_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_BET", values?: undefined): string;
  encodeFunctionData(functionFragment: "MIN_BET", values?: undefined): string;
  encodeFunctionData(functionFragment: "bonusPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "chainlinkOracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimWinnings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "emergencyWithdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundBonusPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAIPrediction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMatchStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPlatformStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPredictionDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserBet",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStats",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBet",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "matchBets",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "matchPool",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "placeBet",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "predictions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setChainlinkOracle",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "settleMatch",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitAIPrediction",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "totalBonusesPaid",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMatchesCorrect",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalMatchesPredicted",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolumeTraded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userBetIndex",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userCorrectPredictions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalBets",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userTotalWinnings",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "winnersCount",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BONUS_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MAX_BET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MIN_BET", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bonusPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "chainlinkOracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "emergencyWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundBonusPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAIPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMatchStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPlatformStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPredictionDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUserBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matchBets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matchPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "placeBet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "predictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setChainlinkOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleMatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitAIPrediction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalBonusesPaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMatchesCorrect",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalMatchesPredicted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolumeTraded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userBetIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userCorrectPredictions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalBets",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userTotalWinnings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "winnersCount",
    data: BytesLike
  ): Result;
}

export namespace AIPredictionSubmittedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    homeTeam: string,
    awayTeam: string,
    predictedHomeScore: BigNumberish,
    predictedAwayScore: BigNumberish,
    confidence: BigNumberish,
    matchStartTime: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    homeTeam: string,
    awayTeam: string,
    predictedHomeScore: bigint,
    predictedAwayScore: bigint,
    confidence: bigint,
    matchStartTime: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    homeTeam: string;
    awayTeam: string;
    predictedHomeScore: bigint;
    predictedAwayScore: bigint;
    confidence: bigint;
    matchStartTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BetPlacedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    user: AddressLike,
    amount: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    user: string,
    amount: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    user: string;
    amount: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BonusPoolFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MatchSettledEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    actualHomeScore: BigNumberish,
    actualAwayScore: BigNumberish,
    aiWasCorrect: boolean,
    totalPool: BigNumberish,
    winnersCount: BigNumberish,
    bonusPerWinner: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    actualHomeScore: bigint,
    actualAwayScore: bigint,
    aiWasCorrect: boolean,
    totalPool: bigint,
    winnersCount: bigint,
    bonusPerWinner: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    actualHomeScore: bigint;
    actualAwayScore: bigint;
    aiWasCorrect: boolean;
    totalPool: bigint;
    winnersCount: bigint;
    bonusPerWinner: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OracleAddressUpdatedEvent {
  export type InputTuple = [oldOracle: AddressLike, newOracle: AddressLike];
  export type OutputTuple = [oldOracle: string, newOracle: string];
  export interface OutputObject {
    oldOracle: string;
    newOracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinningsClaimedEvent {
  export type InputTuple = [
    matchId: BigNumberish,
    user: AddressLike,
    betAmount: BigNumberish,
    bonus: BigNumberish,
    total: BigNumberish
  ];
  export type OutputTuple = [
    matchId: bigint,
    user: string,
    betAmount: bigint,
    bonus: bigint,
    total: bigint
  ];
  export interface OutputObject {
    matchId: bigint;
    user: string;
    betAmount: bigint;
    bonus: bigint;
    total: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PredictionMarket extends BaseContract {
  connect(runner?: ContractRunner | null): PredictionMarket;
  waitForDeployment(): Promise<this>;

  interface: PredictionMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BONUS_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  MAX_BET: TypedContractMethod<[], [bigint], "view">;

  MIN_BET: TypedContractMethod<[], [bigint], "view">;

  bonusPool: TypedContractMethod<[], [bigint], "view">;

  chainlinkOracleAddress: TypedContractMethod<[], [string], "view">;

  claimWinnings: TypedContractMethod<
    [matchId: BigNumberish],
    [void],
    "nonpayable"
  >;

  emergencyWithdraw: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundBonusPool: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getAIPrediction: TypedContractMethod<
    [matchId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        homeScore: bigint;
        awayScore: bigint;
        confidence: bigint;
      }
    ],
    "view"
  >;

  getMatchStats: TypedContractMethod<
    [matchId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalPool: bigint;
        totalBets: bigint;
        winners: bigint;
      }
    ],
    "view"
  >;

  getPlatformStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        matchesPredicted: bigint;
        matchesCorrect: bigint;
        volume: bigint;
        bonusesPaid: bigint;
        currentBonusPool: bigint;
        aiAccuracy: bigint;
      }
    ],
    "view"
  >;

  getPredictionDetails: TypedContractMethod<
    [matchId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        homeTeam: string;
        awayTeam: string;
        predictedHomeScore: bigint;
        predictedAwayScore: bigint;
        confidence: bigint;
        matchStartTime: bigint;
        settled: boolean;
        aiWasCorrect: boolean;
      }
    ],
    "view"
  >;

  getUserBet: TypedContractMethod<
    [matchId: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  getUserStats: TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalBets: bigint;
        totalWinnings: bigint;
        correctPredictions: bigint;
      }
    ],
    "view"
  >;

  hasBet: TypedContractMethod<
    [matchId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  matchBets: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        amount: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  matchPool: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  placeBet: TypedContractMethod<
    [matchId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  predictions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        boolean
      ] & {
        homeTeam: string;
        awayTeam: string;
        predictedHomeScore: bigint;
        predictedAwayScore: bigint;
        confidence: bigint;
        matchStartTime: bigint;
        predictionTimestamp: bigint;
        exists: boolean;
        settled: boolean;
        actualHomeScore: bigint;
        actualAwayScore: bigint;
        aiWasCorrect: boolean;
      }
    ],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setChainlinkOracle: TypedContractMethod<
    [_oracle: AddressLike],
    [void],
    "nonpayable"
  >;

  settleMatch: TypedContractMethod<
    [
      matchId: BigNumberish,
      actualHomeScore: BigNumberish,
      actualAwayScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitAIPrediction: TypedContractMethod<
    [
      matchId: BigNumberish,
      homeTeam: string,
      awayTeam: string,
      predictedHomeScore: BigNumberish,
      predictedAwayScore: BigNumberish,
      confidence: BigNumberish,
      matchStartTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  totalBonusesPaid: TypedContractMethod<[], [bigint], "view">;

  totalMatchesCorrect: TypedContractMethod<[], [bigint], "view">;

  totalMatchesPredicted: TypedContractMethod<[], [bigint], "view">;

  totalVolumeTraded: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdc: TypedContractMethod<[], [string], "view">;

  userBetIndex: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  userCorrectPredictions: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  userTotalBets: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userTotalWinnings: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  winnersCount: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BONUS_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BET"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "bonusPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "chainlinkOracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimWinnings"
  ): TypedContractMethod<[matchId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "emergencyWithdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundBonusPool"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAIPrediction"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        homeScore: bigint;
        awayScore: bigint;
        confidence: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMatchStats"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        totalPool: bigint;
        totalBets: bigint;
        winners: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPlatformStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        matchesPredicted: bigint;
        matchesCorrect: bigint;
        volume: bigint;
        bonusesPaid: bigint;
        currentBonusPool: bigint;
        aiAccuracy: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPredictionDetails"
  ): TypedContractMethod<
    [matchId: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, boolean, boolean] & {
        homeTeam: string;
        awayTeam: string;
        predictedHomeScore: bigint;
        predictedAwayScore: bigint;
        confidence: bigint;
        matchStartTime: bigint;
        settled: boolean;
        aiWasCorrect: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserBet"
  ): TypedContractMethod<
    [matchId: BigNumberish, user: AddressLike],
    [
      [bigint, bigint, boolean] & {
        amount: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStats"
  ): TypedContractMethod<
    [user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalBets: bigint;
        totalWinnings: bigint;
        correctPredictions: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasBet"
  ): TypedContractMethod<
    [matchId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchBets"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, bigint, bigint, boolean] & {
        user: string;
        amount: bigint;
        timestamp: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchPool"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "placeBet"
  ): TypedContractMethod<
    [matchId: BigNumberish, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "predictions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        bigint,
        boolean
      ] & {
        homeTeam: string;
        awayTeam: string;
        predictedHomeScore: bigint;
        predictedAwayScore: bigint;
        confidence: bigint;
        matchStartTime: bigint;
        predictionTimestamp: bigint;
        exists: boolean;
        settled: boolean;
        actualHomeScore: bigint;
        actualAwayScore: bigint;
        aiWasCorrect: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setChainlinkOracle"
  ): TypedContractMethod<[_oracle: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleMatch"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      actualHomeScore: BigNumberish,
      actualAwayScore: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitAIPrediction"
  ): TypedContractMethod<
    [
      matchId: BigNumberish,
      homeTeam: string,
      awayTeam: string,
      predictedHomeScore: BigNumberish,
      predictedAwayScore: BigNumberish,
      confidence: BigNumberish,
      matchStartTime: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalBonusesPaid"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMatchesCorrect"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalMatchesPredicted"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolumeTraded"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "userBetIndex"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userCorrectPredictions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTotalBets"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userTotalWinnings"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "winnersCount"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getEvent(
    key: "AIPredictionSubmitted"
  ): TypedContractEvent<
    AIPredictionSubmittedEvent.InputTuple,
    AIPredictionSubmittedEvent.OutputTuple,
    AIPredictionSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "BetPlaced"
  ): TypedContractEvent<
    BetPlacedEvent.InputTuple,
    BetPlacedEvent.OutputTuple,
    BetPlacedEvent.OutputObject
  >;
  getEvent(
    key: "BonusPoolFunded"
  ): TypedContractEvent<
    BonusPoolFundedEvent.InputTuple,
    BonusPoolFundedEvent.OutputTuple,
    BonusPoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "MatchSettled"
  ): TypedContractEvent<
    MatchSettledEvent.InputTuple,
    MatchSettledEvent.OutputTuple,
    MatchSettledEvent.OutputObject
  >;
  getEvent(
    key: "OracleAddressUpdated"
  ): TypedContractEvent<
    OracleAddressUpdatedEvent.InputTuple,
    OracleAddressUpdatedEvent.OutputTuple,
    OracleAddressUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "WinningsClaimed"
  ): TypedContractEvent<
    WinningsClaimedEvent.InputTuple,
    WinningsClaimedEvent.OutputTuple,
    WinningsClaimedEvent.OutputObject
  >;

  filters: {
    "AIPredictionSubmitted(uint256,string,string,uint8,uint8,uint8,uint256)": TypedContractEvent<
      AIPredictionSubmittedEvent.InputTuple,
      AIPredictionSubmittedEvent.OutputTuple,
      AIPredictionSubmittedEvent.OutputObject
    >;
    AIPredictionSubmitted: TypedContractEvent<
      AIPredictionSubmittedEvent.InputTuple,
      AIPredictionSubmittedEvent.OutputTuple,
      AIPredictionSubmittedEvent.OutputObject
    >;

    "BetPlaced(uint256,address,uint256,uint256)": TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;
    BetPlaced: TypedContractEvent<
      BetPlacedEvent.InputTuple,
      BetPlacedEvent.OutputTuple,
      BetPlacedEvent.OutputObject
    >;

    "BonusPoolFunded(address,uint256)": TypedContractEvent<
      BonusPoolFundedEvent.InputTuple,
      BonusPoolFundedEvent.OutputTuple,
      BonusPoolFundedEvent.OutputObject
    >;
    BonusPoolFunded: TypedContractEvent<
      BonusPoolFundedEvent.InputTuple,
      BonusPoolFundedEvent.OutputTuple,
      BonusPoolFundedEvent.OutputObject
    >;

    "MatchSettled(uint256,uint8,uint8,bool,uint256,uint256,uint256)": TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;
    MatchSettled: TypedContractEvent<
      MatchSettledEvent.InputTuple,
      MatchSettledEvent.OutputTuple,
      MatchSettledEvent.OutputObject
    >;

    "OracleAddressUpdated(address,address)": TypedContractEvent<
      OracleAddressUpdatedEvent.InputTuple,
      OracleAddressUpdatedEvent.OutputTuple,
      OracleAddressUpdatedEvent.OutputObject
    >;
    OracleAddressUpdated: TypedContractEvent<
      OracleAddressUpdatedEvent.InputTuple,
      OracleAddressUpdatedEvent.OutputTuple,
      OracleAddressUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "WinningsClaimed(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
    WinningsClaimed: TypedContractEvent<
      WinningsClaimedEvent.InputTuple,
      WinningsClaimedEvent.OutputTuple,
      WinningsClaimedEvent.OutputObject
    >;
  };
}
